environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - echo %npm_config_debug%
  - npm install

test_script:
  - npm test
  
